apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-management
  template:
    metadata:
      labels:
        app: employee-management
    spec:
      containers:
      - name: employee-management
        image: eeshanidocker/employee-management-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
