apiVersion: v1
kind: Service
metadata:
  name: employee-management-service
spec:
  type: NodePort
  selector:
    app: employee-management
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
